# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{todorb}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rahul Kumar"]
  s.date = %q{2010-06-20}
  s.default_executable = %q{todorb}
  s.description = %q{command-line program that manages a todo list text file }
  s.email = %q{sentinel1879@gmail.com}
  s.executables = ["todorb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "README.markdown",
     "VERSION",
     "lib/common/colorconstants.rb",
     "lib/common/sed.rb",
     "lib/todorb.rb"
  ]
  s.homepage = %q{http://github.com/rkumar/todorb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{command-line todo list manager}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

